## the fconsta_pipeline only downloads from UniProt, but there are several putative bacteriocins we'd like to search, which you can download here
## NOTE: You'll need to manually concatenate this with the protein_sequences.fasta generated by the main pipeline.
## Also!!! ONLY RUN THIS FROM THE EXTRA FOLDER AS THE WORKING DIRECTORY!!!!
from Bio import Entrez
import pandas as pd
import os
Entrez.email="example_email@unil.ch"

gene_list = pd.read_csv("extra_gene_list.csv")
print(gene_list)
output = open("sequences.fasta", "a")


for gene in gene_list["Gene"]:
    print("Downloading gene: " + gene)
    stream = Entrez.esearch(db="protein", term = "Streptococcus[Orgn] AND " + gene + "[Gene]")
    record = Entrez.read(stream)

    for id in record["IdList"]:
        stream = Entrez.efetch(db="protein", id = id, rettype="fasta", retmode="text")
        entry = stream.read()
        old_entry = entry.split("\n")[0]
        sequence = entry.split("\n")[1]
        new_entry = ">" + gene + "|" + entry.split(".")[0].split(">")[1] + "\n" + sequence + "\n\n"
        output.write(new_entry)


